# Generated by Django 3.1.4 on 2020-12-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201221_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='thumbnails',
        ),
    ]
